export const FEATURED_HANDLES: string[] = [
  'gaearon',
  'sebmarkbage',
  'acdlite',
  'sophiebits',
  'rickhanlonii',
  'bvaughn',
  'trueadm',
  'aweary',
  'eps1lon',
  'threepointone',
  'rauchg',
  'leerob',
  'shuding',
  'timneutkens',
  'styfle',
  'ijjk',
  'huozhi',
  'samcx',
  'balazsorban44',
  'kdy1',
  'sindresorhus',
  'karpathy',
  'tj',
  'addyosmani',
  'paulirish',
  'mjackson',
  'ryanflorence',
  'kentcdodds',
  'wesbos',
  'sdras',
  'tannerlinsley',
  'tkdodo',
  'markerikson',
  'daishi',
  'drcmda',
  'satya164',
  'brentvatne',
  'mrousavy',
  'cassidoo',
  'jaredpalmer',
  'mxstbr',
  'kettanaito',
  'evanw',
  'developit',
  'antfu',
  'danielroe',
  'yyx990803',
  'rich-harris',
  'torvalds',
  'mitchellh',
  'kelseyhightower',
  'shadcn',
  'pacocoursey',
  'steveruizok',
  'aurorascharff',
];

const FEATURED_HANDLE_SET = new Set(FEATURED_HANDLES);

export function isFeaturedHandle(handle: string): boolean {
  return FEATURED_HANDLE_SET.has(handle.toLowerCase());
}
